from enum import StrEnum


class UsuarioStatus(StrEnum):
    ATIVO = "ATIVO"
    INATIVO = "INATIVO"
    BLOQUEADO = "BLOQUEADO"


class CategoriaStatus(StrEnum):
    ATIVA = "ATIVA"
    INATIVA = "INATIVA"


class AnuncioStatus(StrEnum):
    ATIVO = "ATIVO"
    ESGOTADO = "ESGOTADO"
    ENCERRADO = "ENCERRADO"


class ModalidadeEntrega(StrEnum):
    ENTREGA = "ENTREGA"
    RETIRADA = "RETIRADA"


class PedidoStatus(StrEnum):
    AGUARDANDO_PAGAMENTO = "AGUARDANDO_PAGAMENTO"
    PAGAMENTO_APROVADO = "PAGAMENTO_APROVADO"
    PREPARANDO_ENTREGA = "PREPARANDO_ENTREGA"
    EM_ENTREGA = "EM_ENTREGA"
    ENTREGUE = "ENTREGUE"
    EM_CONTESTACAO = "EM_CONTESTACAO"
    CONCLUIDO = "CONCLUIDO"
    CANCELADO = "CANCELADO"
    REEMBOLSADO = "REEMBOLSADO"


class ProvedorPagamento(StrEnum):
    MERCADO_PAGO = "MERCADO_PAGO"


class ContaPagamentoStatus(StrEnum):
    PENDENTE = "PENDENTE"
    ATIVA = "ATIVA"
    BLOQUEADA = "BLOQUEADA"
    DESCONECTADA = "DESCONECTADA"


class MetodoPagamento(StrEnum):
    PIX = "PIX"
    CARTAO_CREDITO = "CARTAO_CREDITO"
    CARTAO_DEBITO = "CARTAO_DEBITO"
    BOLETO = "BOLETO"


class PagamentoStatus(StrEnum):
    CRIADO = "CRIADO"
    PENDENTE = "PENDENTE"
    EM_PROCESSAMENTO = "EM_PROCESSAMENTO"
    APROVADO = "APROVADO"
    RECUSADO = "RECUSADO"
    CANCELADO = "CANCELADO"
    REEMBOLSADO_PARCIAL = "REEMBOLSADO_PARCIAL"
    REEMBOLSADO = "REEMBOLSADO"


class EntregaStatus(StrEnum):
    AGUARDANDO_ENVIO = "AGUARDANDO_ENVIO"
    PREPARANDO = "PREPARANDO"
    EM_ROTA = "EM_ROTA"
    ENTREGUE = "ENTREGUE"
    RECUSADA = "RECUSADA"
    CANCELADA = "CANCELADA"


class RepasseStatus(StrEnum):
    AGUARDANDO_ENTREGA = "AGUARDANDO_ENTREGA"
    EM_PERIODO_CONTESTACAO = "EM_PERIODO_CONTESTACAO"
    BLOQUEADO = "BLOQUEADO"
    PRONTO_PARA_LIBERACAO = "PRONTO_PARA_LIBERACAO"
    PROCESSANDO = "PROCESSANDO"
    PAGO = "PAGO"
    FALHOU = "FALHOU"
    CANCELADO = "CANCELADO"
    REEMBOLSADO = "REEMBOLSADO"


class ContestacaoMotivo(StrEnum):
    PEDIDO_NAO_RECEBIDO = "PEDIDO_NAO_RECEBIDO"
    PRODUTO_DANIFICADO = "PRODUTO_DANIFICADO"
    QUANTIDADE_INCORRETA = "QUANTIDADE_INCORRETA"
    PRODUTO_DIFERENTE = "PRODUTO_DIFERENTE"
    ENTREGA_PARCIAL = "ENTREGA_PARCIAL"
    OUTRO = "OUTRO"


class ContestacaoStatus(StrEnum):
    ABERTA = "ABERTA"
    EM_ANALISE = "EM_ANALISE"
    AGUARDANDO_VENDEDOR = "AGUARDANDO_VENDEDOR"
    ACEITA = "ACEITA"
    RECUSADA = "RECUSADA"
    CANCELADA = "CANCELADA"
    RESOLVIDA = "RESOLVIDA"


class ReembolsoStatus(StrEnum):
    SOLICITADO = "SOLICITADO"
    PROCESSANDO = "PROCESSANDO"
    CONCLUIDO = "CONCLUIDO"
    RECUSADO = "RECUSADO"
    FALHOU = "FALHOU"
    CANCELADO = "CANCELADO"


class EventoProcessamentoStatus(StrEnum):
    PENDENTE = "PENDENTE"
    PROCESSADO = "PROCESSADO"
    FALHOU = "FALHOU"
    IGNORADO = "IGNORADO"
